# Generated by Django 5.1.2 on 2024-11-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imageURL', models.URLField()),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home')], default='', max_length=20)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField()),
                ('listingClosed', models.BooleanField()),
            ],
        ),
    ]
